api/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'check-stock/(?P<item_id>\d+)/$', check_stock, name='check_stock'),

    url(r'push/$', payment_push),
    url(r'success/$', payment_success, name="payment_success"),

]

fasttech/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from shop.views import page404
handler404 = page404

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shop.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^pages/', include('cms.urls')),
    url(r'^user/', include('userapp.urls')),
    url(r'^manager/', include('manager.urls', namespace="manager")),
    url(r'^chat/', include('consult.urls', namespace="consult")),
    url(r'^help/', include('knowledge.urls', namespace="knowledge")),
]

knowledge/urls.py
from django.conf.urls import url
from .views import *

app_name = "knowledge"
urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^(?P<action>my)/$', index, name="index"),
    url(r'^ask/$', AskView.as_view(), name="ask"),
    url(r'^category/(?P<category_id>\d+)/$', category, name="category"),
    url(r'^question/(?P<question_id>\d+)/$', question, name="question"),
    url(r'^question/(?P<question_id>\d+)/delete/$', question_delete, name="question_delete"),

    url(r'^question/(?P<question_id>\d+)/edit/$', question_edit, name="question_edit"),

    url(r'^response/(?P<response_id>\d+)/edit/$', response_edit, name="response_edit"),
    url(r'^response/(?P<question_id>\d+)/$', response, name="response"),
    url(r'^response/moderate/(?P<response_id>\d+)/(?P<action>hide|accept)/$',
        response_moderate, name="response_moderate"),
    url(r'^question/moderate/(?P<question_id>\d+)/(?P<action>hide|accept|open|close)/$',
        question_moderate, name="question_moderate"),
]

manager/urls.py
from django.conf.urls import include, url

from manager.views import *
app_name = "manager"
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^orders/new/$', new_orders, name='new_orders'),
    url(r'^user/orders/(?P<user_pk>\d+)/$', user_orders,
        name='user_orders'),

    url(r'^reviews/new/$', new_reviews, name='new_reviews'),
    url(r'^review_approve$', review_approve, name='review_approve'),

    url(r'^video-reviews/new/$', new_video_reviews, name='new_video_reviews'),
    url(r'^video-review_approve$', video_review_approve,
        name='video_review_approve'),

    url(r'^orders/old/$', old_orders, name='old_orders'),
    url(r'^orders/all/$', orders, name='orders'),
    url(r'^order/(?P<order_pk>\d+)/$', order_info, name='order_info'),
    url(r'^orders/add-item-to-order/(?P<order_pk>\d+)/', add_item_to_order,
        name='add_item_to_order'),
    url(r'^orders/remove-item-from-order/(?P<order_item_pk>\d+)/',
        remove_item_from_order, name='remove_item_from_order'),

    url(r'^emailservice/all/$', email_list, name='email_list'),
    url(r'^emailservice/sms/$', sms_list, name='sms_list'),

    url(r'^coupon/all/$', coupon_list, name='coupon_list'),
    url(r'^coupon/add/$', coupon_edit, name='coupon_edit'),
    url(r'^coupon/(?P<coupon_pk>\d+)/$', coupon_edit, name='coupon_edit'),

    url(r'^money-coupon/all/$', money_coupon_list, name='money_coupon_list'),
    url(r'^money-coupon/add/$', money_coupon_edit, name='money_coupon_edit'),
    url(r'^money-coupon/(?P<coupon_pk>\d+)/$', money_coupon_edit,
        name='money_coupon_edit'),


    
    url(r'order/(?P<order_pk>\d+)/shipment/add/$', shipment_add,
        name="shipment_add"),
    url(r'shipment/(?P<shipment_pk>\d+)/$', shipment_info, name="shipment_info"),

    url(r'^parse-stat$', parse_stat, name='parse_stat'),
    url(r'^search-order$', search_order, name='search_order'),
    
]

templates/fasttech.com/404-main.html
{% extends "home.html" %}
{% block pre_content %}
<div style="width:100%;">
  <div style="position:absolute;" id="image404"><img src="{{ STATIC_URL }}img/sad-zoidberg.jpg" width="200px;"/></div>
  <div style="width:100%; text-align:center; margin:auto 0; font-size:5em;" class="p-title">404</div>
  <div style="width:100%; text-align:center; margin:auto 0;" class="p-title">Страница не найдена<br /> Рекомендуем посмотреть:
<br />
  </div>
</div>
{% endblock %}

templates/fasttech.com/base.html
{% load banertag %}
<!doctype html>
<html class="no-js" lang="ru">
	<head>
		<!--
			 __          _       _      _ _       _    
			 / _|        | |     | |    | (_)     | |   
			 | |_ __ _ ___| |_ ___| | __ | |_ _ __ | | __
			 |  _/ _` / __| __/ _ \ |/ / | | | '_ \| |/ /
			 | || (_| \__ \ ||  __/   < _| | | | | |   < 
			 |_| \__,_|___/\__\___|_|\_(_)_|_|_| |_|_|\_\
             webii.space
		-->
		<meta charset="utf-8">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<title>{% block title %}Электронные сигареты, онлайн-магазин FasteK | Fasttech на русском{% endblock %}</title>

		<meta name="description" content="{% block description %}{% endblock %}">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="apple-touch-icon" href="{{ STATIC_URL }}img/icon2.png?dd">
		<link rel="icon" href="{{ STATIC_URL }}img/icon2.png?dd24">
		<link href="https://fonts.googleapis.com/css?family=Open+Sans|Open+Sans+Condensed:300|PT+Sans" rel="stylesheet"> 
		<link rel="stylesheet" href="{{ STATIC_URL }}css/normalize.css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/main.css?1">
		
		<link rel="stylesheet" href="{{ STATIC_URL }}css/pure-min.css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/grids-responsive-min.css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/style.css?v=12">
		<!--[if gt IE 8]><!-->
		<link rel="stylesheet" href="https://unpkg.com/purecss@0.6.2/build/grids-responsive-min.css">
		<!--<![endif]-->
		
		{% get_baner header %}
		{% block extra_headers %}{% endblock %}
		<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
		
	</head>
	<body>
		<!--[if lt IE 8]>
			<style>
			body {
			font-family: "Comic Sans MS", "Comic Sans", cursive;
			}
			</style>
			<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
		<![endif]-->

		<div class="pure-g main">
			<div class="pure-u-1 header">
				{% block header %}
					<div class="pure-u-md-4-24 logo"> <!-- logo -->
						<a href="/" class="cats"><img alt="ФАСТЕК" src="{{ STATIC_URL }}img/logo-n.png" class="pure-img logo-img" width="190px"/></a>
					</div>
					<div class="pure-u-md-19-24 header2"> 
						<div class="pure-u-1 form">
							<div class="pure-u-1">
								<div class="pure-u-sm-12-24 menu3">
									{% load menu %}
									{% get_menu %}
									{% for p in menu %}
										{% if p.top_menu %}
											<a href="{% url 'page' url=p.url %}">
												{% if p.icon %}<img src="{{ p.icon.url }}" width="30px" /> {% endif %} {{ p }}</a>
										{% endif %}
									{% endfor %}
								</div>
								<div class="menu2 pure-u-sm-12-24">
									{% if not user.is_authenticated %}<a href="{% url 'login' %}">Вход</a>{% else %}
										{% if user.is_staff %}
											<a href="{% url 'manager:index' %}"><img src="{{ STATIC_URL}}img/batman.png" width="25px" /></a>
										{% endif %}
										<a href="{% url 'orders_history' %}"><img src="{{ STATIC_URL }}img/order.png" width="20px" /> Заказы</a>
										<a title="Аккаунт" href="{% url 'account' %}"><img src="{{ STATIC_URL }}img/profile.png" width="20px" /> Аккаунт</a>

										<a title="Выход" href="{% url 'logout' %}"><img src="{{ STATIC_URL }}img/login.png" width="20px" /> Выход</a>
									{% endif %}

									<a title="Корзина" href="{% url 'basket' %}"><img src="{{ STATIC_URL }}img/basket.png" width="20px" /> <span id="basket-amount">?</span></a>

								</div>
								
							</div>
							<form class="pure-form" action="{% url 'search' %}">
								<fieldset>
									<input type="text" name="q" class="pure-input-2-3" placeholder="Введите текст для поиска" {% if q %}value="{{ q }}"{% endif %}>
									<button type="submit" class="pure-button pure-button-primary">Найти товар</button>
								</fieldset>
							</form>
							
						</div>
						<div class="pure-u-1 menu">
							{% load menu %}
							{% get_categories_list %}
							<div class="pure-menu pure-menu-horizontal custom-can-transform">
								<ul class="pure-menu-list">
									{% for top in categories_list %}
										<li class="pure-menu-item pure-menu-has-children">
											<a href="#" id="menuLink{{ top.pk }}" class="pure-menu-link">{{ top }}</a>
											<ul class="pure-menu-children">
												{% for c in top.active_categories %}
													<li class="pure-menu-item">
														<a class="pure-menu-link" href="{% url 'category' cat_name=c.name %}">{{ c.name_rus }} ({{ c.count }})</a>
													</li>
												{% endfor %}
											</ul>
										</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</div>
				{% endblock %}
			</div>
			<div class="pure-u-1 content">
				{% get_baner base_content %}
	
	{% block content %}
	{% endblock %}
	<br />&nbsp;<br />
	<br />&nbsp;<br />
	<br />&nbsp;<br />
      </div>
    </div>
    
    <div id="footer">
		{% block footer %}
		{% include "footer.html" %}
                {% block scripts %}
                {% endblock %}

		{% endblock %}
	</div>
  </body>
</html>

templates/fasttech.com/category.html
{% extends "base.html" %}
{% block title %}Электронные сигареты: {{ c.name_rus }} страница #{{ page.number }}{% endblock %}
{% block content %}

	<h1 class="p-title">Категория: {{ c.name_rus }}  #{{ page.number }}</h1>

	<div class="pure-u-1 sort">
	  сортировать по
          {% for s in sorts %}
          <a {% if sort == s.sort or sort == s.bsort %}class='sort-selected'{% endif %}
            href="?s={% if sort == s.sort %}{{ s.bsort }}{% else %}{{ s.sort }}{% endif %}">{{ s.title }}{% if sort == s.sort or sort == s.bsort %}{% if sort == s.sort %}↓{% else %}↑{% endif %}
          {% endif %}
          </a> &nbsp;
          {% if forloop.last %}{% else %}{% endif %}         
          {% endfor %}
	</div>
	{% for item in page %}
		{% include "item-list.html" %}
	{% endfor %}
	{% include "paginator.html" %}
{% endblock %}

templates/fasttech.com/counters.html
{% load banertag %}
{% get_baner counters %}

templates/fasttech.com/delivery.html
<div class="pure-u-1">
	<h2>Последние отправления:</h2>
	<!-- <h4>Среднее время доставки дней: {{ avg_time }}</h4>-->
	<table class="pure-table">
		<thead>
			<tr>
				<th>#</th>
				<th>Отправлен</th>
				<th>В город</th>
				<th>Дней в пути</th>
				<th>Статус отправления</th>
			</tr>
		</thead>

		<tbody>
			{% for p in parcels %}
				<tr {% if p.is_delivered %}style="background-color:#BEFF25;"{% endif %}>
					<td>{{ forloop.counter }}</td>
					<td>{{ p.added|date:'d M' }}</td>
					<td>{{ p.order.user.registereduser.city }}</td>
					<td {% if p.is_delivered %}style="font-weight:bold;"{% endif %}>{{ p.get_total_time }}</td>
					<td>
						{% if p.is_delivered %}Товар доставлен{% else %}В пути{% endif %}
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

templates/fasttech.com/footer.html
{% load menu %}
<div class="menu1 pure-u-2-5">
	{% get_menu %}
	{% for p in menu %}
		<a href="{% url 'page' url=p.url %}">{% if p.icon %}<img src="{{ p.icon.url }}" width="30px" /> {% endif %}{{ p }}</a>
	{% endfor %}
</div>
<hr />



Мы вконтакте: <a target="_blank" href="https://vk.com/fastek.link"><img src="{{ STATIC_URL }}/img/vk.png" width="40px;" /></a>
Пишите: <a href="mailto:support@fastek.link">support@fastek.link</a>
<br /><br />

<img src="{{ STATIC_URL }}img/logo1.png" width="50px" alt="ФАСТЕК"/>
<a href="//www.free-kassa.ru/"><img src="//www.free-kassa.ru/img/fk_btn/17.png"></a>

<script src="{{ STATIC_URL }}js/vendor/modernizr-2.8.3.min.js"></script>
<script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/vendor/jquery-1.12.0.min.js"><\/script>')</script>
<script src="{{ STATIC_URL }}js_opt/plugins.js"></script>
<script src="{{ STATIC_URL }}js_opt/menus.js"></script>
<script>
$( document ).ready(function() {
	$.get('{% url 'basket_amount' %}' , function( data ) {
		$('#basket-amount').html(data.amount);
	});
});

</script>
{% block footer_add %}
    {% include "counters.html" %}
    {% include "consult/chat.html" %}
{% endblock %}

templates/fasttech.com/home.html
{% extends "base.html" %}
{% block content %}
{% block pre_content %}
{% endblock %}


	{% for items in home_items %}
		<div style="width:70%; text-align:center; margin:0 auto;"><a href="{% url 'category' cat_name=items.cat_name %}"><h2 class="p-title">{{ items.name }}:</h2></a></div>
		{% for item in items.q %}
			{% include "item-list.html" %}
		{% endfor %}
		<div style="width:90%; font-size:1.2em; text-align:right;" class="p-title"><a style="color:#D40000;" href="{% url 'category' cat_name=items.cat_name %}"> листать дальше >>>  </a></div>
		<hr />
	{% endfor %}
	<hr />
	<h2 class="p-title"><a href="{% url 'new' %}">Все товары</a></h2>

	<hr />
	<br />
	{% include "delivery.html" %}

{% endblock %}

templates/fasttech.com/item-list.html
{% load humanize %}
<div class="pure-u-lg-7-24  pure-u-md-11-24 item pure-u-sm-4-5 item-list">
  <div class="pure-u-1 list-title">
    <h3 class="title" title="{{ item.title }}"><a href="{% url 'item' item_name=item.title item_pk=item.pk %}">{{ item.get_title }}</a></h3>
  </div>
  <div class="pure-u-1 info-block">
    <div class="info pure-u-3-5">
      <a href="{% url 'category' cat_name=item.category.name %}">{{ item.category.name_rus }}</a>
    </div>
    <div class="pure-u-7-24 price">
      <a class="price" {% if sort == "price" or sort == "-price" %}style="font-size:1em; font-weight:bold;"{% endif %}>{{ item.get_price }}<b>&nbsp;⃏</b></a>
    </div>
  </div>
  <div class="media">
    <a href="{% url 'item' item_name=item.title item_pk=item.pk %}">
      <img src="{{ item.get_thumb }}" class="pure-img" />
    </a>
    <div class="rate" style="width: {{ item.get_rate_width }}px;" title="Рейтинг: {{ item.rate }} из 5 на основе {{ item.total_votes }} голосов">
      &#9733;&#9733;&#9733;&#9733;&#9733;
    </div>
    {% if item.date_listed %}
    <div class="added_info" title="Добавлено на сайт" {% if sort == "date_listed" or sort == "-date_listed" %}style="color:#D40000; font-size:1em; font-weight:bold;"{% endif %}>
      {{ item.date_listed|naturalday }}
    </div>
    {% endif %}
  </div>
  {% if user.is_staff %}
	  <div class="admin-edit-panel">
		  <div class="admin-edit-item">
			  <a target="_blank" href="{{ item.url.url }}"><img src="{{ STATIC_URL }}img/link.png" width="20px" /></a>
		  </div>
		  <div class="">
			  <a href="{% url 'admin:shop_item_change' item.id %}"><img src="{{ STATIC_URL }}img/edit.png" width="25px" /></a>
		  </div>
	  </div>
  {% endif %}

</div>

templates/fasttech.com/item-small-list.html
<div class="pure-u-1">
	<span class="related-title" title="{{ item.title }}"><a href="{% url 'item' item_name=item.title item_pk=item.pk %}">{{ item.get_title }} - {{ item.get_price }} <b class="price"> ⃏</b></a></span>
	<div class="media">
		<a href="{% url 'item' item_name=item.title item_pk=item.pk %}"><img src="{{ item.get_thumb }}" class="pure-img"/></a>
	</div>
</div>

templates/fasttech.com/item.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}Купить {% if item.title %}{{ item.title_rus }} - {% endif %}{{ item.title }}{% endblock %}
{% block extra_headers %}
	<link rel="canonical" href="{{ SITE_URL_NO_SLASH }}{% url 'item' item_name=item.title item_pk=item.pk %}" />
{% endblock %}
{% block content %}
<div class="pure-g">
  <div class="pure-u-1">
    <div class="pure-u-md-17-24">
      <h3 class="title" title="{{ item.title }}"><a href="">{{ item.get_title }}</a></h3>
      <div class="pure-u-1">
		  {% if item.title_rus %}<h6 class="sub">({{ item.title }})</h6>{% endif %}
        <h6 class="sub">{% if item.sub_title_rus %}{{ item.sub_title_rus }}{% endif %} <a href="#desc">подробнее &darr;</a></h6>
      </div>

    </div>
    <div class="pure-u-md-5-24">
      <a class="pointer" onclick="$('#ask-form').show();">Задать вопрос по товару</a>

      <div class="pure-u-2-5 basket-p" id="ask-form" style="display:none;">

          <div class="pure-u-3-24 pointer" style="float:right; text-align:right;"><img onclick="$('#ask-form').hide();" src="{{ STATIC_URL }}img/close.png" width="30px" /></div>
		  {% if user.is_authenticated %}
          <form class="pure-form pure-form-stacked" method="post" action="{% url 'knowledge:ask' %}">{% csrf_token %}
          {{ question_item_form.as_p }}
          <input type="submit" value="Задать вопрос" />
          </form>
          {% else %}
          Чтобы задать вопрос, вы должны быть зарегистрированы.<br />

          <a href="{% url 'login' %}">Войдите</a> на сайт используя адрес электронной почты.
        {% endif %}

      </div>

      
    </div>
    <div class="pure-u-1 info-block">
      <div class="info pure-u-3-5">
	<a href="{% url 'category' cat_name=item.category.name %}">{{ item.category.name_rus }}</a>
      </div>
    </div>


    <div class="pure-u-1">
      <div class="media pure-u-lg-17-24 pure-u-md-1-1">
	<img src="{{ item.get_photo }}" id="main-img" class="pure-img"/>
	<div class="pure-g">
	  <br />	  
	  {% for photo in item.photos.all %}
	  <div class="pure-u-lg-3-24 pure-u-md-1-5 pure-u-sm-1-5" onmouseover="$('#main-img').attr('src', '{{ photo.get_url }}');">
	    <img src="{{ photo.get_thumb }}" class="pure-img-responsive item-mini-photo" width="100%"/>
	    {% if user.is_staff %}
	    <div style="font-size:8px;">
	      {% if photo.is_main %}
	      Главное фото
	      {% else %}
	      <a href="{% url 'set_main_photo' photo_pk=photo.pk item_pk=item.pk %}?next={% url 'item' item_name=item.title item_pk=item.pk %}">Выбрать главным</a>

	      {% endif %}
	    </div>
	    {% endif %}

	  </div>
	  {% endfor %}
	</div>

      </div>
      <div class="pure-u-lg-6-24 pure-u-md-1-1 buy-div">
	<h4 class="main-price" title="Стоимость">{{ item.get_price }}<b class="price"> ⃏</b></h4>

        
	<div class="pure-u-2-5 basket-p" id="basket-added"  style="display:none;">
	  <div class="pure-u-20-24"><b>Товар добавлен в корзину!</b></div>
	  <div class="pure-u-3-24" style="float:right; text-align:right;"><img class="pointer" onclick="$('#basket-added').hide();" src="{{ STATIC_URL }}img/close.png" width="30px" /></div>

	  <b class="green">{{ item.title_rus }}</b>
	  <img src="{{ item.get_photo }}" class="pure-img" />
	  Всего товаров в корзине: <b><span id="total-amount"></span></b><br />

	  <a class="pure-button" href="{% url 'basket' %}">Корзина</a>
	</div>


	<span id="add-spinner" style="display:none;"><img src="{{ STATIC_URL }}img/spinner.gif" /></span>
	<span id="check_avail"><b>Проверяем наличие ...</b> <img src="{{ STATIC_URL }}img/spinner.gif" /></span>
	<span id="not_avail" style="display:none;">Нет в наличии</span>
	<span id="buy_btn" style="display:none;">
	  <a id="add-button-wrap" class="pure-button button-success" onclick="add_basket({{ item.pk }});">
	    <b id="add-button">Добавить в корзину</b>
	  </a>
	</span>
	<!-- 	<h4>Информация:</h4> -->
	<br /><b>Наличие:</b> <span id="avail"><img src="{{ STATIC_URL }}img/spinner.gif" /></span>
	<span id="long-wait-warning" style="color:red; display:none;" >
		<br />Внимание! Товара нет на нашем складе, но есть на складе фабрики. Если вы не готовы ждать, то просьба выбрать другой товар, со статусом «в наличии».<br />
		<span style="text-decoration:underline;" class="pointer" onclick="$('#detail-wait').toggle();" >подробнее</span>
		<span id="detail-wait" style="display:none;" >
			<br />
			Указано приблизительное время доставки товара на наш склад. После этого товар будет выслан на ваш адрес.
			<br />Обратите внимание, что это не значит, что сроки будут соблюдены, т.к. данные о сроках предоставляет фабрика, и мы не можем никак на них повлиять, в случае задержки.
			<br />
			Хотя в некоторых случаях фабрики и выполняют свои обещания по срокам, имейте ввиду, что время доставки товара может задержаться до месяца.
			
		</span>
	</span>
	<br />
	<hr />
	Тип: <b>{{ item.product_type }}</b><br />
	{% if item.color %}Цвет: <b>{{ item.color }}</b><br />{% endif %}
	<br />
	Материал:<b> {{ item.material }}</b><br />

      </div>
    </div>


    <div class="pure-g">
      <div class="pure-u-1">
	<br />
	<hr />
	
	<div class="pure-u-14-24 pure-u-md-14-24 pure-u-sm-1-1">
	  <h2><a id="reviews" href="#reviews">Отзывы:</a></h2>
	  <div class="pure-u-1">
	    {% for r in reviews %}
	    <div class="review-item">
	      <div class="review-nickname {% if r.is_owner %}review-nickname-owner {% endif %}pure-u-6-24">
		{{ r.nickname }}
		{% if r.is_owner %}
		<br />
		<div class="nickname-info">
		  отзыв покупателя
		</div>
		{% endif %}
	      </div>
	      <div class="review-text pure-u-14-24">
		{{ r.text }}
	      </div>
	    </div>
	    {% empty %}
	    Отзывов пока нет, будьте первым:
	    {% endfor %}
	    {% if added %}
	    <br />
	    <div class="pure-u-1-1 button-success">Ваш отзыв добавлен, он будет доступен после модерации.</div>
	    <br />
	    {% endif %}
	    <form class="pure-form pure-form-stacked review-form" action="{% url 'add_review' item_pk=item.pk %}" method="post">{% csrf_token %}
	    <fieldset>
	      {{ form.as_p }}
              <span class='form-h'><input type="text" name="email" /></span>
	      <button type="submit" class="pure-button pure-button-primary">Добавить</button>
	    </fieldset>
	    </form>
	  </div>
	  <hr />

	  Видео обзоры:<br />
	  {% for v in video_reviews %}
	  <iframe width="560" height="315" src="{{ v.get_embed_code }}" frameborder="0" allowfullscreen></iframe>
	  <hr />
	  {% empty %}
	  Видео обзоров пока нет.
	  {% endfor %}
	  <h2><a id="desc" href="#desc">Описание:</a></h2>
	  {% for pr in item.item_properties.all %}
	  {% ifchanged pr.property_type %}<h4>{{ pr.property_type }}:</h4>{% endifchanged %}
	  <div style="padding-left:20px;" class="pure-u-1">
	    <b title="{{ pr.property_name }}">{{ pr.property_name }}:</b> <span title="{{ pr.property_value }}">{{ pr.property_value }} </span><br />
	  </div>
	  {% endfor %}
	  <br />
	  {% if item.date_listed %}
	  <div style="padding-top:10px;">
	    Добавлено: {{ item.date_listed|naturalday }}
	  </div>
	  {% endif %}
	  <span style="font-size:0.5em"> #{{ item.sku }}</span>
	</div>

	<div class="pure-u-lg-8-24 pure-u-sm-1 related-wrapper">
	  <h2><b id="related" href="#related">Смотрите также:</a></b></h2>
	  <div class="pure-u-1 related">
	    {% for r in related %}
	    {% include "item-small-list.html" with item=r.related_item %}
	    {% endfor %}
	  </div>
	</div>
      </div>
    </div>
  </div>


  {% if user.is_staff %}
  
  <div class="admin-edit-panel pure-u-1">
    <div class="admin-edit-item">
      <a target="_blank" href="{{ item.url.url }}">
	🔗 
      </a>
      <a href="{% url 'admin:shop_item_change' item.id %}">
	✎ 
      </a>
      <a href="{% url 'redirect_item' item_pk=item.pk %}" rel="nofollow">
	i
      </a>
    </div>
  </div>
  {% endif %}
</div>


<script>
 $( document ).ready(function() {
	 $.get('{% url 'check_stock' item_id=item.pk %}' , function( data ) {
	     $('#avail').html(data.stock);
	     $('#check_avail').hide();
	     if (data.stock_i == 1){
			 $('#buy_btn').show()
			 if (data.stock_q == false){
				 $('#long-wait-warning').show();
			 }
	     } else {
			 $('#not_avail').show()
			 
	     }
	 });
 });

 function add_basket(item_id) {
	 $('#add-spinner').show();
	 $('#add-button').hide();
	 $.get('{% url 'add_item' item_id=item.pk %}' , function( data ) {
		 $('#total-amount').html(data.total);
	 }).done(function() {
		 $('#add-spinner').hide();
		 $('#add-button').show();
		 $('#basket-added').show();
	 }).fail(function() {
		 $('#add-spinner').hide();
		 $('#add-button').show();
		 alert( "Ошибка добавления в корзину, попробуйте позже" );
	 });
	 
 }
</script>
{% endblock %}

templates/fasttech.com/new.html
{% extends "base.html" %}
{% block title %}Новые поступления: страница #{{ page.number }} (vape, mechmods, моды, электронки){% endblock %}
{% block content %}

	<h2 class="p-title">Новые поступления #{{ page.number }}:</h2>

	{% for item in page %}
		{% include "item-list.html" %}
	{% endfor %}
	{% include "paginator.html" %}


{% endblock %}