api/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'check-stock/(?P<item_id>\d+)/$', check_stock, name='check_stock'),

    url(r'push/$', payment_push),
    url(r'success/$', payment_success, name="payment_success"),

]

fasttech/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from shop.views import page404
handler404 = page404

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shop.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^pages/', include('cms.urls')),
    url(r'^user/', include('userapp.urls')),
    url(r'^manager/', include('manager.urls', namespace="manager")),
    url(r'^chat/', include('consult.urls', namespace="consult")),
    url(r'^help/', include('knowledge.urls', namespace="knowledge")),
]

manager/urls.py
from django.conf.urls import include, url

from manager.views import *
app_name = "manager"
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^orders/new/$', new_orders, name='new_orders'),
    url(r'^user/orders/(?P<user_pk>\d+)/$', user_orders,
        name='user_orders'),

    url(r'^reviews/new/$', new_reviews, name='new_reviews'),
    url(r'^review_approve$', review_approve, name='review_approve'),

    url(r'^video-reviews/new/$', new_video_reviews, name='new_video_reviews'),
    url(r'^video-review_approve$', video_review_approve,
        name='video_review_approve'),

    url(r'^orders/old/$', old_orders, name='old_orders'),
    url(r'^orders/all/$', orders, name='orders'),
    url(r'^order/(?P<order_pk>\d+)/$', order_info, name='order_info'),
    url(r'^orders/add-item-to-order/(?P<order_pk>\d+)/', add_item_to_order,
        name='add_item_to_order'),
    url(r'^orders/remove-item-from-order/(?P<order_item_pk>\d+)/',
        remove_item_from_order, name='remove_item_from_order'),

    url(r'^emailservice/all/$', email_list, name='email_list'),
    url(r'^emailservice/sms/$', sms_list, name='sms_list'),

    url(r'^coupon/all/$', coupon_list, name='coupon_list'),
    url(r'^coupon/add/$', coupon_edit, name='coupon_edit'),
    url(r'^coupon/(?P<coupon_pk>\d+)/$', coupon_edit, name='coupon_edit'),

    url(r'^money-coupon/all/$', money_coupon_list, name='money_coupon_list'),
    url(r'^money-coupon/add/$', money_coupon_edit, name='money_coupon_edit'),
    url(r'^money-coupon/(?P<coupon_pk>\d+)/$', money_coupon_edit,
        name='money_coupon_edit'),


    
    url(r'order/(?P<order_pk>\d+)/shipment/add/$', shipment_add,
        name="shipment_add"),
    url(r'shipment/(?P<shipment_pk>\d+)/$', shipment_info, name="shipment_info"),

    url(r'^parse-stat$', parse_stat, name='parse_stat'),
    url(r'^search-order$', search_order, name='search_order'),
    
]

manager/models.py
from django.db import models

# Create your models here.

manager/forms.py
# -*- coding: utf-8 -*-
import hashlib

from django.conf import settings
from django import forms
from django.forms import HiddenInput, Textarea
from django.forms import ModelForm, Form
from django.contrib.auth.models import User
from django.contrib.admin import widgets
from userapp.models import Order, RegisteredUser, Shipment, OrderItem, Coupon, \
    MoneyCoupon


class ShipmentForm(forms.ModelForm):
    class Meta:
        model = Shipment
        fields = ("tracking", "orderitem", "photo", "order")
        widgets = {'order': forms.HiddenInput()}

    def __init__(self, *args, **kwargs):
        super(ShipmentForm, self).__init__(*args, **kwargs)
        self.fields['orderitem'].queryset = OrderItem.objects.filter(\
                                            order=self.initial['order'])
        
class CouponForm(forms.ModelForm):
    class Meta:
        model = Coupon
        exclude = ("added", "used_count",)

    def __init__(self, *args, **kwargs):
        super(CouponForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].widget = forms.TextInput(\
                                        attrs={"class":"date_field"})
        self.fields['end_date'].widget = forms.TextInput(\
                                        attrs={"class":"date_field"})
        

class MoneyCouponForm(forms.ModelForm):
    class Meta:
        model = MoneyCoupon
        exclude = ("added", )


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ("is_done", "is_sended", "is_processed",  "is_payed",
                  "estimated_send_date", "manager_remark", "is_deleted",
                  "fasttech_order_url", )

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['estimated_send_date'].widget = forms.TextInput(\
                                            attrs={"class":"date_field"})

class ItemSkuForm(forms.Form):
    sku = forms.CharField(label="SKU", max_length=30)
    

manager/views.py
# -*- coding: utf-8 -*-
""" userapp views"""

from datetime import datetime
import hashlib
import json


from django.core.mail import send_mail
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.conf import settings
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import reverse
from django.db.models import Q

from djangohelpers.utils import gen_url
from emailuser.models import EmailUserForm, manual_create_email_user
from userapp.models import *
from shop.models import ParseStat
from emailservice.models import EmailObject, SmsObject
from .forms import OrderForm, ShipmentForm, CouponForm, ItemSkuForm
from shop.functions import prepare_page

@staff_member_required
def new_orders(request):
    items = Order.objects.filter(is_payed=True, is_processed=False,
                                 is_deleted=False).order_by("-id")
    page, page_range = prepare_page(request, items)
    
    return render(request, "manager/new-orders.html",
                  {"page":page, "page_range":page_range, "new":True})

@staff_member_required
def orders(request):
    items = Order.objects.filter(is_done=False,
                                 is_deleted=False).order_by("-id")
    page, page_range = prepare_page(request, items)
    
    return render(request, "manager/new-orders.html",
                  {"page":page, "page_range":page_range, "new":False})

@staff_member_required
def old_orders(request):
    items = Order.objects.filter(is_payed=True,
                                 is_done=True).order_by("-id")
    page, page_range = prepare_page(request, items)
    
    return render(request, "manager/new-orders.html",
                  {"page":page, "page_range":page_range, "new":False,
                   "old":True})


@staff_member_required
def add_item_to_order(request, order_pk):
    order = get_object_or_404(Order, pk=order_pk)
    form = ItemSkuForm(request.POST)
    if form.is_valid():
        item = get_object_or_404(Item, sku=form.cleaned_data['sku'])
        order_item = OrderItem(item=item, order=order)
        order_item.save()
    return HttpResponseRedirect(reverse('manager:order_info',
                                        kwargs={"order_pk":order.pk}))

@staff_member_required
def remove_item_from_order(request, order_item_pk):
    order_item = get_object_or_404(OrderItem, pk=order_item_pk)
    order_item.delete()
    return HttpResponseRedirect(reverse('manager:order_info',
                                        kwargs={"order_pk":order_item.order.pk}))

@staff_member_required
def order_info(request, order_pk):
    order = get_object_or_404(Order, pk=order_pk)
    order_items = OrderItem.objects.filter(order=order)
    order_user = order.user.registereduser

    total_user_orders = Order.objects.filter(user=order.user,
                                             is_payed=True).count()
    if request.method == "POST":
        order_form = OrderForm(request.POST, instance=order)
        if order_form.is_valid():
            order_form.save()
    else:
        order_form = OrderForm(instance=order)
    sku_form = ItemSkuForm()
    return render(request, "manager/order.html",
                  {"order":order, "order_items":order_items,
                   "order_user":order_user, "order_form":order_form,
                   "total_user_orders": total_user_orders,
                   "sku_form":sku_form,
                   })


@staff_member_required
def email_list(request):
    items = EmailObject.objects.all().order_by("-id")
    page, page_range = prepare_page(request, items)
    return render(request, "manager/email-list.html",
                  {"page":page, "page_range":page_range})

@staff_member_required
def sms_list(request):
    items = SmsObject.objects.all().order_by("-id")
    page, page_range = prepare_page(request, items)
    return render(request, "manager/sms-list.html",
                  {"page":page, "page_range":page_range})

@staff_member_required
def new_reviews(request):
    reviews = Review.objects.filter(is_active=True, is_moderated=False)
    return render(request, "manager/reviews.html", {"reviews":reviews})

@staff_member_required
def review_approve(request):
    pk = request.GET.get("review_id", False)
    apr = request.GET.get("do", False)
    review = Review.objects.get(pk=pk)
    if apr == "approve":
        review.is_moderated = True
    if apr == "delete":
        review.is_active = False
    review.save()
    return HttpResponseRedirect(reverse('manager:new_reviews'))

@staff_member_required
def user_orders(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    orders = Order.objects.filter(user__user=user, is_payed=True)
    return render(request, "manager/user-orders.html",
                  {"orders":orders, "o_user":user})

@staff_member_required
def shipment_add(request, order_pk):
    order = get_object_or_404(Order, pk=order_pk)
    order_items = OrderItem.objects.filter(order=order)
    if request.method == "POST":
        form = ShipmentForm(request.POST,  request.FILES, initial={"order":order})
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('manager:order_info', kwargs={"order_pk":order.pk}))
    else:
        form = ShipmentForm(initial={"order":order})
    
    return render(request, "manager/shipment-add.html", locals())

@staff_member_required
def shipment_info(request, shipment_pk):
    shipment = get_object_or_404(Shipment, pk=shipment_pk)
    try:
        post_tr = PostTracker.objects.get(shipment=shipment)
    except PostTracker.DoesNotExist:
        post_tr = False
    else:
        post_tr_items = PostTrackerItem.objects.filter(posttracker=post_tr).order_by("date")
    return render(request, "manager/shipment-info.html", locals())

@staff_member_required
def coupon_list(request):
    coupons = Coupon.objects.filter()
    return render(request, "manager/coupon-list.html", {"coupons":coupons})


@staff_member_required
def coupon_edit(request, coupon_pk=False):
    if coupon_pk:
        coupon = get_object_or_404(Coupon, pk=coupon_pk)
    else:
        coupon = None
    saved = request.GET.get("saved", False)

    if request.method == "POST":
        form = CouponForm(request.POST, instance=coupon)
        if form.is_valid():
            instance = form.save()
            return HttpResponseRedirect("%s?saved=True" % (reverse('manager:coupon_edit',
                                                                   kwargs={"coupon_pk":instance.pk})))
    else:
        form = CouponForm(instance=coupon)
    
    return render(request, "manager/coupon-edit.html",
                  {"form":form, "coupon":coupon, "saved":saved})

@staff_member_required
def parse_stat(request):
    last_parse = ParseStat.objects.filter().order_by("-id")[:10]
    return render(request, "manager/parse-stat.html", {"parse_stat":last_parse})


@staff_member_required
def new_video_reviews(request):
    video_reviews = VideoReview.objects.filter(is_active=True, is_moderated=False)
    page, page_range = prepare_page(request, video_reviews, 1)
    
    return render(request, "manager/video-reviews.html",
                  {"video_reviews":page, "page_range":page_range})

@staff_member_required
def video_review_approve(request):
    pk = request.GET.get("review_id", False)
    apr = request.GET.get("do", False)
    review = VideoReview.objects.get(pk=pk)
    if apr == "approve":
        review.is_moderated = True
        review.is_active = True
    if apr == "delete":
        review.is_moderated = True
        review.is_active = False
    review.save()

    try:
        video_review = VideoReview.objects.filter(is_active=True, is_moderated=False)[0]
    except IndexError:
        video_review = []
        
    return render(request, "manager/video-review-item.html",
                  {"review":video_review})

@staff_member_required
def index(request):
    reviews = Review.objects.filter(is_moderated=False,
                                    is_active=True).count()
    video_reviews = VideoReview.objects.filter(is_moderated=False,
                                               is_active=True).count()
    video_reviews_moderated = VideoReview.objects.filter(is_moderated=True).count()
    
    new_orders = Order.objects.filter(is_payed=True, is_processed=False,
                                      is_deleted=False).count()
    
    orders = Order.objects.filter(is_payed=True, is_done=False,
                                 is_deleted=False).count()
    old_orders = Order.objects.filter(is_payed=True, is_done=True).count()
    
    return render(request, "manager/index.html", locals())



@staff_member_required
def money_coupon_list(request):
    coupons = MoneyCoupon.objects.filter()
    return render(request, "manager/money-coupon-list.html", {"coupons":coupons})


@staff_member_required
def money_coupon_edit(request, coupon_pk=False):
    if coupon_pk:
        coupon = get_object_or_404(MoneyCoupon, pk=coupon_pk)
    else:
        coupon = None
    saved = request.GET.get("saved", False)

    if request.method == "POST":
        form = MoneyCouponForm(request.POST, instance=coupon)
        if form.is_valid():
            instance = form.save()
            return HttpResponseRedirect("%s?saved=True" % (reverse('manager:money_coupon_edit',
                                                                   kwargs={"coupon_pk":instance.pk})))
    else:
        form = MoneyCouponForm(instance=coupon)
    
    return render(request, "manager/money-coupon-edit.html",

templates/fasttech.com/manager/base.html
{% extends "base.html" %}
{% block title %}Панель менеджера{% endblock %}
{% block extra_headers %}

{% endblock %}

{% block header %}
<div class="pure-g">
  <div style="padding:3px;" class="pure-u-1">
    <div class="pure-menu pure-menu-horizontal">
      <ul class="pure-menu-list">
	<li class="pure-menu-item">
	  <a href="/"><img src="{{ STATIC_URL }}img/batman.png" width="30px" /></a>
	  <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
	    <a href="#" id="menuLink1" class="pure-menu-link">Заказы:</a>
	    <ul class="pure-menu-children">
	      <li class="pure-menu-item">

		<a class="pure-menu-link" href="{% url 'manager:new_orders' %}">Новые</a>									
	      </li>
	      <li class="pure-menu-item">
		<a class="pure-menu-link" href="{% url 'manager:orders' %}">В работе</a>
	      </li>
	      <li class="pure-menu-item">
		<a class="pure-menu-link" href="{% url 'manager:old_orders' %}">Старые</a>					
	      </li>
	      
	    </ul>
	  </li>
	</li>
	
	<li class="pure-menu-item">
	  <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
	    <a href="#" id="menuLink2" class="pure-menu-link">Логи:</a>
	    <ul class="pure-menu-children">
	      <li class="pure-menu-item">
		<a class="pure-menu-link" href="{% url 'manager:email_list' %}">Почта</a>
	      </li>
	      <li class="pure-menu-item">
		<a class="pure-menu-link" href="{% url 'manager:sms_list' %}">SMS</a>					
	      </li>
	      <li class="pure-menu-item">
		<a class="pure-menu-link" href="{% url 'manager:parse_stat' %}">Статистика парсинга</a>
	      </li>
	    </ul>
	  </li>
	</li>


	<li class="pure-menu-item">
	  <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
	    <a href="#" id="menuLink3" class="pure-menu-link">Админ:</a>
	    <ul class="pure-menu-children">
	      <li class="pure-menu-item">
		<a class="pure-menu-link" href="{% url 'manager:new_reviews' %}">Отзывы</a>					
	      </li>
	      <li class="pure-menu-item">
		<a class="pure-menu-link" href="{% url 'manager:new_video_reviews' %}">Видео-обзоры</a>					
	      </li>
	      <li class="pure-menu-item">
		<a class="pure-menu-link" href="{% url 'manager:coupon_list' %}">Купоны</a>					
	      </li>
	      <li class="pure-menu-item">
		<a class="pure-menu-link" href="{% url 'manager:money_coupon_list' %}">Денежные Купоны</a>					
	      </li>
	    </ul>
	  </li>
	</li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}{% endblock %}
{% block footer_add %}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <script>
    $( function() {
    $( ".date_field" ).datepicker({
    dateFormat: "dd.mm.yy"
    });
    } );
  </script>

  {% block footer_scripts %}
  
  {% endblock %}

  {% endblock %}

templates/fasttech.com/manager/coupon-list.html
{% extends "manager/base.html" %}
{% block title %}Купоны{% endblock %}
{% block content %}


	{% if user.is_staff %}
	<h2>Купоны:</h2>

	<table class="pure-table pure-table-horizontal">
		<thead>
			<tr>
				<th>#</th>
				<th>Название купона</th>
                <th>Купон</th>
				<th>Скидка</th>
				<th>Минимальная сумма</th>
				<th>Создан</th>
				<th>Действителен</th>
				<th>Использован раз</th>
				<th>-</th>
			</tr>
		</thead>
		<tbody>
			{% for c in coupons %}
				<tr>
				<td>{{ forloop.counter }}</td>
				<td><a href="{% url 'manager:coupon_edit' coupon_pk=c.pk %}">{{ c.title }}</a></td>
                <td>{{ c.name }}</td>
				<td>{{ c.discount }}%</td>
				<td>{{ c.min_sum }}</td>
				<td>{{ c.added }}</td>
				<td>{% if c.start_date %}с {% endif %}{{ c.start_date }}
					<br />{% if c.end_date %}по {% endif %}{{ c.end_date }}</td>
				<td>{{ c.used_count }}</td>
				<td>-</td>
					
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endif %}

{% endblock %}

templates/fasttech.com/manager/email-list.html
{% extends "manager/base.html" %}
{% block title %}Почта{% endblock %}
{% block content %}


	{% if user.is_staff %}
	<h2>Письма:</h2>

	<table class="pure-table pure-table-horizontal">
		<thead>
			<tr>
				<th>#</th>
				<th>Адрес</th>
                                <th>Дата создания</th>
				<th>Письмо</th>
				<th>Отправлено</th>
				<th>Ошибка</th>
			</tr>
		</thead>
		<tbody>
			{% for email in page %}
				{% include "manager/email-item.html" %}
			{% endfor %}
		</tbody>
	</table>
	{% include "paginator.html" %}

{% endif %}

{% endblock %}

templates/fasttech.com/manager/index.html
{% extends "manager/base.html" %}
{% block title %}Moderator Dashboard{% endblock %}
{% block content %}

{% if user.is_staff %}

    <div class="pure-u-1 dashboard">
		<h3>Заказы <img src="{{ STATIC_URL }}img/zoidberg-read.png" width="40px" /></h3>
		 новые: <a href="{% url 'manager:new_orders' %}">{{ new_orders }}</a>
		 в работе: <a href="{% url 'manager:orders' %}">{{ orders }}</a>
		 старые: <a href="{% url 'manager:old_orders' %}">{{ old_orders }}</a>
		<hr />
		<h3>Модерация  <img src="{{ STATIC_URL }}img/zoidberg-angry.png" width="70px" /></h3>
		Отзывы: <a href="{% url 'manager:new_reviews' %}">{{ reviews }}</a>
		Видео-обзоры: <a title="Отмодерировано обзоров: {{ video_reviews_moderated }}" href="{% url 'manager:new_video_reviews' %}">{{ video_reviews }}</a>
	</div>	 
        
{% endif %}

{% endblock %}

templates/fasttech.com/manager/new-orders.html
{% extends "manager/base.html" %}
{% block title %}История заказов{% endblock %}
{% block content %}

	<form action="{% url 'manager:search_order' %}" method="get">
		<label>Поиск заказа: </label><input type="text" name="query" {% if q %} value="{{ q }}"{% endif %} />
		<input type="submit" value ="Ok" />
	</form>
	<br />
	{% if user.is_staff %}
		{% if q %}
			<h2>Результаты поиска: {{ q }}</h2>
		{% else %}
			{% if old %}Полученные клиентами заказы:{% else %}
				<h2>{% if new %}Новые заказы:{% else %} <img src="{{ STATIC_URL }}img/money.png" width="30px" /> Все оплаченные заказы:{% endif %}</h2>
			{% endif %}
		{% endif %}
	<table class="pure-table pure-table-horizontal">
		<thead>
			<tr>
				<th>#</th>
				<th>Заказ</th>
                                <th>ФИО</th>
				<th>Сумма</th>
				<th>Контакты</th>
				<th>Состояние</th>
			</tr>
		</thead>
		<tbody>
			{% for order in page %}
				{% include "manager/order-item.html" %}
			{% endfor %}
		</tbody>
	</table>

	{% include "paginator.html" %}
{% endif %}

{% endblock %}


{% block footer %}
    {% if new %}
      {% for order in page %}
        {% if forloop.counter == 1 %}
          <center>
            <img src="{{ STATIC_URL }}img/zoidberg.jpg" width="100px" />
          </center>
        {% endif %}
        {% empty %}
          <center>
            <img src="{{ STATIC_URL }}img/sad-zoidberg.jpg" width="100px"/>
          </center>
      {% endfor %}
      {% else %}
          <center>
            <img src="{{ STATIC_URL }}img/zoidberg2.jpg" width="100px"/>
          </center>
      
    {% endif %}

{% endblock %}

templates/fasttech.com/manager/order.html
{% extends "manager/base.html" %}
{% block title %}Заказ {{ order.pk }}{% endblock %}
{% block content %}

{% if user.is_staff %}

	<h2>Заказ {{ order.pk }}:</h2>
    <div class="pure-u-1">

      {% if order.track_status %}<h3>Статус отправления: {{ order.track_status }}</h3>{% endif %}

      {% if order.pay_date %}<div class="pure-u-1" title="Дата оплаты">(Оплачено: {{ order.pay_date|date:"SHORT_DATE_FORMAT" }})</div>{% endif %}
		
      <div class="pure-u-1">
        Пользователь: {{ order_user.user.user }}
        <a href="{% url 'manager:user_orders' user_pk=order.user.user.pk %}">({{ order.total_orders }})</a>
      </div>
      
      {% if order_user.last_name %}
		  <div class="delivery-info">Фамилия:</div> <b>{{ order_user.last_name }}</b><br />
	  {% endif %}

      {% if order_user.first_name %}
		  <div class="delivery-info">Имя:</div>     <b>{{ order_user.first_name }}</b><br />
      {% endif %} 
      {% if order_user.patronymic %}
		  <div class="delivery-info">Отчество:</div> <b>{{ order_user.patronymic }}</b><br />
      {% endif %}

      {% if order_user.country %}
		  <div class="delivery-info">Страна:</div>  <b>{{ order_user.country.name }}</b><br />{% endif %}

	  
      {% if order_user.zip %}
		  <div class="delivery-info">Индекс:</div>  <b>{{ order_user.zip }}</b><br />{% endif %}
		  {% if order_user.city %}
		  <div class="delivery-info">Город: </div>  <b>{{ order_user.city }}</b><br />{% endif %}
		  {% if order_user.address %}
			  <div class="delivery-info">Адрес: </div>  <b>{{ order_user.address }}</b><br />
		  {% endif %}
		  <div class="delivery-info">Телефон:</div> <b>{{ order.user.registereduser.phone }}</b><br />

	  	  <div class="delivery-info">
			  Усиленная упаковка:
		  </div>
		  <b>
			  {% if order.strong_package %}
				  ДА
			  {% else %}
				  НЕТ
			  {% endif %}
		  </b>
		  <hr />

	</div>
    <div class="pure-u-1">
		<table class="pure-table pure-table-horizontal">
			<thead>
				<tr>
					<th>#</th>
					<th>Фото</th>
					<th>Наименование</th>
					<th>Цена</th>
					<th>Кол-во</th>
					<th>Стоимость</th>
                                        <th>Фастек:</th>
				</tr>
			</thead>
			<tbody>
				{% for item in order_items %}
					
					<tr>
						<td style="font-size:1.4em">
							{{ forloop.counter }}
						</td>
						<td>
							<a href="{% url 'item' item_name=item.item.title item_pk=item.item.pk %}">
								<img src="{{ item.item.get_photo }}" class="pure-img" width="150px" />
							</a>
						</td>
						<td style="font-size:0.9em;">
							<a href="{% url 'item' item_name=item.item.title item_pk=item.item.pk %}">{{ item.item.title_rus }}</a>

							<br />
							<a style="color:red;" href="{% url 'manager:remove_item_from_order' order_item_pk=item.pk %}" title="Удалить товар из заказа">Удалить</a>
						</td>
						<td>
							{{ item.item.get_price }}&nbsp;<b class="price">⃏</b>
						</td>
						<td>
							<b>{{ item.amount }}</b>
						</td>

						<td>
							{{ item.get_total_price }}&nbsp;<b class="price">⃏</b>
						</td>

                        <td>
                            <a target="_blank" href="{{ item.item.url.url }}">{{ item.item.url.url }}</a>
                        </td>

					</tr>
				{% empty %}
					Заказ пуст
				{% endfor %}

				<tr>
					<td>
					</td>
					<td colspan="3" style="text-align:right; font-size:1.3em;">Итого (оплачено):</td>
					<td colspan="3" style="font-size:1.3em;">{{ order.total_payed }}  <b class="price"> ⃏</b></td>
				</tr>
				<tr>
					<td></td>
					<td colspan="3" style="text-align:right; font-size:1.3em;">Итого (стоимость заказа):</td>
					<td colspan="3" style="font-size:1.3em;">{{ order.price }}  <b class="price"> ⃏</b></td>
					
				</tr>
				{% if order.money_coupon %}
				<tr>
					<td>
					</td>
					<td colspan="3" style="text-align:right; font-size:1.1em;">Использован денежный купон (<b>{{ order.money_coupon }}</b>)</td>
					<td colspan="3" style="font-size:1.1em;">Оплачено деньгами: {{ order.total_payed }} <b class="price"> ⃏</b></td>
				</tr>
				{% endif %}
			</tbody>
		</table>
		<br />
		{% if order.fasttech_order_url %}Ссылка на заказ: <a href="{{ order.fasttech_order_url }}">{{ order.fasttech_order_url }}</a><br />{% endif %}
			<hr />
		<form action="{% url 'manager:add_item_to_order' order_pk=order.pk %}" method="post">{% csrf_token %}
			Добавить товар к заказу:<br />
			{{ sku_form.as_p }}
			<input type="submit" value="Добавить товар" />
		</form>
		<br />
		{% if order.user_comment %}
			<h3>Комментарий к заказу:</h3>
			<pre class="user-comment">{{ order.user_comment }}</pre>
		{% endif %}
		
		<h3>Состояние заказа: {{ order.get_status }}</h3>
		{% if order.tracking %}
			Отслеживание отправления: <a target="_blank" href="https://www.pochta.ru/Tracking#{{ order.tracking }}">{{ order.tracking }}</a>
        </div>
		{% endif %}

		<hr />

                Отправления: <br />
                <ul>
                  {% for sh in order.shipments %}
                  <li>

                    <a href="{% url 'manager:shipment_info' shipment_pk=sh.pk %}">{{ sh.get_track_status }}</a>

                  </li>
                  {% endfor %}
                </ul>
                <br />
                <a href="{% url 'manager:shipment_add' order_pk=order.pk %}">Добавить отправление</a>
                <br />
		<form id="order_form" action="" method="post" class="pure-form pure-form-aligned">{% csrf_token %}
			<fieldset> 

				<div class="pure-control-group">
					{% for field in order_form %}
						<div class="fieldWrapper">
							{{ field.errors }}
							{{ field.label_tag }} {{ field }}
							{% if field.help_text %}
								<p class="help">{{ field.help_text|safe }}</p>
							{% endif %}
						</div>
					{% endfor %}

				</div>
			</fieldset>
			<div class="pure-controls">
				<button class="pure-button pure-button-primary" id="id_login" type="submit">Сохранить</button></p>
			</div>
		</form>



        
{% endif %}

{% endblock %}