api/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'check-stock/(?P<item_id>\d+)/$', check_stock, name='check_stock'),

    url(r'push/$', payment_push),
    url(r'success/$', payment_success, name="payment_success"),

]

consult/urls.py
from django.conf.urls import include, url

from consult.views import *
app_name = "consult"
urlpatterns = [
    url(r'^message/add/$', message_add, name='message_add'),
    url(r'^message/update/$', message_update, name='message_update'),
]

fasttech/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from shop.views import page404
handler404 = page404

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shop.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^pages/', include('cms.urls')),
    url(r'^user/', include('userapp.urls')),
    url(r'^manager/', include('manager.urls', namespace="manager")),
    url(r'^chat/', include('consult.urls', namespace="consult")),
    url(r'^help/', include('knowledge.urls', namespace="knowledge")),
]

consult/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.humanize.templatetags.humanize import naturaltime

from userapp.models import SessionUser


class Consultant(models.Model):
    telegram_name = models.CharField(max_length=50, unique=True)
    display_name = models.CharField(max_length=100)
    is_online = models.BooleanField(default=False)

    telegram_chat_id = models.IntegerField(null=True)
    
    def __str__(self):
        return self.telegram_name


class ChatUser(models.Model):
    user = models.ForeignKey(User, null=True, blank=True,
                             on_delete=models.CASCADE)
    tuser = models.ForeignKey(Consultant, null=True, blank=True,
                              on_delete=models.CASCADE)
    session_user = models.ForeignKey(SessionUser, null=True, blank=True,
                                     on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now=True)

    def get_display_name(self):
        """Return  'display username' or Вы 
        for case user is not registered"""
        if self.user:
            return self.user.email
        elif self.tuser:
            return "Михаил Соколов"
            return self.tuser.display_name
        return "Вы"

    def get_internal_name(self):
        """Return  'display username' or Вы 
        for case user is not registered"""
        if self.user:
            return "%s (ID: %s)" % (self.user.email, self.pk)
        elif self.tuser:
            return "Михаил Соколов"
            return self.tuser.display_name
        return str(self.pk)

    def __str__(self):
        res = self.get_internal_name()
        return res


class Chat(models.Model):
    chatid = models.ForeignKey(ChatUser, related_name="chatid",
                               on_delete=models.CASCADE) # this field is not changed
    # beetwen messages, it is unique for "Chat"
    # so we can get messages for 1 chat only
    user = models.ForeignKey(ChatUser, on_delete=models.CASCADE) # this field changes beetwen
    # messages
    
    message = models.CharField(max_length=1000)
    added = models.DateTimeField(auto_now=True)
    is_sended = models.BooleanField(default=False)

    @property
    def is_user(self):
        if self.user.tuser:
            return False
        else:
            return True
        
    def __str__(self):
        return self.user

    def get_display_time(self):
        return naturaltime(self.added)


class ErrorLog(models.Model):
    message = models.TextField()
    is_sended = models.BooleanField(default=False)
    added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message


class ChatS(models.Model):
    """"""
    consultant = models.ForeignKey(Consultant, on_delete=models.CASCADE)
    chat_user = models.ForeignKey(ChatUser, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return str("%s->%s" % (self.sonsultant, self.chat_user))

consult/forms.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django import forms
from django.forms import HiddenInput, Textarea
from django.forms import ModelForm, Form
from django.contrib.auth.models import User
from django.utils import timezone

from .models import Chat



class ChatForm(forms.ModelForm):

    class Meta:
        model = Chat
        fields = ("message", )

consult/views.py
# -*- coding: utf-8 -*-
import json
from datetime import datetime
import traceback

from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Consultant, Chat, ChatUser
from .forms import ChatForm
from userapp.models import SUser


def message_add(request):
    s_user = SUser(request)
    user = request.user
    if user.is_authenticated:
        chat_user, c = ChatUser.objects.get_or_create(user=user)
    else:
        chat_user, c = ChatUser.objects.get_or_create(session_user=s_user.get_user)
    if request.method == "POST":
        form = ChatForm(request.POST)
        if form.is_valid():
            ch = form.save(commit=False)
            ch.chatid = chat_user
            ch.user = chat_user
            ch.save()
            
    result = {"result":True}
    js = json.dumps(result)
    return HttpResponse(js, content_type='application/json')


@csrf_exempt
def message_update(request):
    s_user = SUser(request).get_user
    user = request.user
    if user.is_authenticated:
        try:
            chat_user, c = ChatUser.objects.get_or_create(user=user)
        except ChatUser.MultipleObjectsReturned:
            ChatUser.objects.filter(user=user).delete()
            chat_user, c = ChatUser.objects.get_or_create(user=user)
            
    else:
        try:
            chat_user, c = ChatUser.objects.get_or_create(session_user=s_user)
        except ChatUser.MultipleObjectsReturned:
            ChatUser.objects.filter(session_user=s_user).delete()
            chat_user, c = ChatUser.objects.get_or_create(session_user=s_user)
    chat_user.added = datetime.now()
    chat_user.save(update_fields=['added',])
    
    chat_messages = Chat.objects.filter(chatid=chat_user).order_by("-added")[:20]
    try:
        js = json.dumps([(str(ch.message), str(ch.user.get_display_name()),
                          str(ch.get_display_time()), ch.is_user)
                         for ch in chat_messages])
    except:
        print(traceback.format_exc())
        print (str([(ch.message, str(ch.user.get_display_name()), ch.get_display_time(),
                      ch.is_user) for ch in chat_messages]))
        js = json.dumps(['Ошибка', '', '', False])
    return HttpResponse(js, content_type='application/json')

templates/fasttech.com/consult/chat.html
<script>
 function chat_start(){
	 window.up_int = setInterval(function(){ update_messages(); }, 1500);
	 $('#chat').show('slow'); $('#chat_preview').hide();
	 $('#chat_preview').removeClass('chat_info');
 }

 function chat_stop(){
	 $('#chat_preview').removeClass('chat_info');
	 $('#chat_preview').show('slow');
	 $('#chat').hide();
	 clearInterval(window.up_int);
 }
</script>
<div id="chat_preview" onclick="chat_start();">
	<img src="{{ STATIC_URL }}img/chat.png" width="20px" />	Консультант
</div>
<div id="chat">
	<div id="chat_title">Консультант: Михаил Соколов <div class="chat_title_ctrls">
		<span id="chat_close" onclick="chat_stop();">➘</span>
	</div>
	</div>
	<div id="chat_win">
	</div>
	<div id="chat_controls">
		<form id="chat_form" action="{% url 'consult:message_add' %}" method="POST">{% csrf_token %}
			<input type="text" id="id_message" name="message" placeholder="Введите сообщение"/>
			<button type="submit">Ок</button>
		</form>
	</div>
</div>
<script>
 function update_messages(){
	 var url = "{% url 'consult:message_update' %}";
	 $.ajax({
		 type: "POST",
		 url: url,
		 data: $("#chat_form").serialize(), 
		 success: function(data)
		 {
			 $('#chat_win').html('');
			 for (var key in data) {
				 if (data.hasOwnProperty(key)) {
					 if (data[key][3] == true){
						 var cls = 'chat_user';
					 } else {
						 var cls = 'chat_cons';
					 }
					 $('#chat_win').append('<div class="chat_element '+cls+'"><span class="chat_username">'+data[key][1]+':</span> <span class="chat_time">' + data[key][2]+ ' </span> <div class="chat_text">'+ data[key][0] + '</div></div>') ;
                     // $('#chat_preview').addClass('chat_info');
                     
                     
				 }
			 }
		 }
	 });
	 
 }

 update_messages();


 $( document ).ready(function() {
	 $("#chat_form").submit(function(e) {
		 var url = "{% url 'consult:message_add' %}";
		 $.ajax({
			 type: "POST",
			 url: url,
			 data: $("#chat_form").serialize(), 
			 success: function(data)
			 {
                 $('#id_message').val(' ');
				 update_messages();
			 }
		 });
		 e.preventDefault(); // avoid to execute the actual submit of the form.
     });
 });
 
</script>