api/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'check-stock/(?P<item_id>\d+)/$', check_stock, name='check_stock'),

    url(r'push/$', payment_push),
    url(r'success/$', payment_success, name="payment_success"),

]

fasttech/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from shop.views import page404
handler404 = page404

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shop.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^pages/', include('cms.urls')),
    url(r'^user/', include('userapp.urls')),
    url(r'^manager/', include('manager.urls', namespace="manager")),
    url(r'^chat/', include('consult.urls', namespace="consult")),
    url(r'^help/', include('knowledge.urls', namespace="knowledge")),
]

knowledge/urls.py
from django.conf.urls import url
from .views import *

app_name = "knowledge"
urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^(?P<action>my)/$', index, name="index"),
    url(r'^ask/$', AskView.as_view(), name="ask"),
    url(r'^category/(?P<category_id>\d+)/$', category, name="category"),
    url(r'^question/(?P<question_id>\d+)/$', question, name="question"),
    url(r'^question/(?P<question_id>\d+)/delete/$', question_delete, name="question_delete"),

    url(r'^question/(?P<question_id>\d+)/edit/$', question_edit, name="question_edit"),

    url(r'^response/(?P<response_id>\d+)/edit/$', response_edit, name="response_edit"),
    url(r'^response/(?P<question_id>\d+)/$', response, name="response"),
    url(r'^response/moderate/(?P<response_id>\d+)/(?P<action>hide|accept)/$',
        response_moderate, name="response_moderate"),
    url(r'^question/moderate/(?P<question_id>\d+)/(?P<action>hide|accept|open|close)/$',
        question_moderate, name="question_moderate"),
]

knowledge/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save
from django.conf import settings
from django.urls import reverse

from djangohelpers.utils import wilson_score

from emailservice.models import EmailObject
from shop.models import Item


class Category(models.Model):
    """Разделы"""
    title = models.CharField(max_length=255)
    added = models.DateTimeField(auto_now_add=True)
    last_changed = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    
    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name = 'Раздел'
        verbose_name_plural = "Разделы"

        
class BaseModel(models.Model):
    """
    The base class for our models.
    """

    added = models.DateTimeField(auto_now_add=True)
    last_changed = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_public = models.BooleanField(default=False)

    vote_plus = models.IntegerField(default=0)
    vote_minus = models.IntegerField(default=0)
    rate = models.FloatField(default=0)


    class Meta:
        abstract = True
        ordering = ['-added']
    
    def save(self, *args, **kwargs):
        if self.vote_plus + self.vote_minus > 0:
            total_votes = self.vote_plus + self.vote_minus
            sum_rate = self.vote_plus
            self.rate = wilson_score(sum_rate, total_votes, [0,1,])
        
        super(BaseModel, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.title

        
class Response(BaseModel):
    description = models.TextField(verbose_name="Ответ",
                                   help_text="Можно использовать markdown")
    
    accepted = models.BooleanField(default=False)
    question = models.ForeignKey('Question', on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['-added']
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"

        
class Question(BaseModel):
    title = models.CharField(max_length=250, verbose_name="Вопрос",
                             help_text="Введите кратко ваш вопрос",)
    description = models.TextField(verbose_name="Описание вопроса",
                                   help_text="Опишите подробнее вопрос, можно использовать markdown")
    
    is_closed = models.BooleanField(default=False) # ответы больше не принимаются
    item = models.ForeignKey(Item, null=True, blank=True,
                             on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category)

    class Meta:
        verbose_name = "Вопрос"
        verbose_name_plural = "Вопросы"

    def response_count(self):
        return Response.objects.filter(accepted=True, question=self).count()

    def response_count_str(self):
        c = self.response_count()
        print (c)
        res = ""
        if c == 0:
            res = " нет ответов"
        elif c in range(5, 21):
            res = "%s ответов" % c
        elif str(c)[-1] == "1":
            res = "%s ответ" % c
        elif int(str(c)[-1]) in [2, 3, 4,]:
            res = "%s ответа" % c
        return res


def new_question(sender, instance, created, **kwargs):
    """ Send email to admins about new question added"""
    if settings.DEBUG:
        return # Ignore sending message for debug version

    if created:
        url = reverse('knowledge:question',
                      kwargs={"question_id":instance.id})
        text = "Новый вопрос в поддержку: %s%s" % (settings.SITE_URL, url)
        for m in settings.MANAGERS:
            eo, c = EmailObject.objects.get_or_create(
                subject="Новый вопрос в поддержку на fastek.link",
                text=text, to=m[1])
        
post_save.connect(new_question, sender=Question)

def new_response(sender, instance, created, **kwargs):
    """ Send email to user about new response added"""
    if settings.DEBUG:
        return # Ignore sending message for debug version

    if not created:
        return

    url = reverse('knowledge:question',
                  kwargs={"question_id":instance.question.id})
    text = "Ваш вопрос получил новый ответ: %s%s"\
           % (settings.SITE_URL, url)

    if instance.user == instance.question.user:
        for m in settings.MANAGERS:
            text = "Новый ответ на fastek.link %s%s"\
                   % (settings.SITE_URL, url)
            eo, c = EmailObject.objects.get_or_create(
                subject="Новый ответ на fastek.link",
                text=text, to=m[1])
        
    else:
        eo, c = EmailObject.objects.get_or_create(
            subject="Новый ответ на сайте %s" % settings.SITE_URL,
            text=text, to=instance.question.user.email)

post_save.connect(new_response, sender=Response)

knowledge/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm, Form


from .models import Question, Response



class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ("title", "description", )

class ResponseForm(ModelForm):
    class Meta:
        model = Response
        fields = ("description", )

class QuestionItemForm(ModelForm):
    class Meta:
        model = Question
        fields = ("description", "item")
        widgets = {
            'item': forms.HiddenInput(),
            'description': forms.Textarea(attrs={'class':
                                                 'question_form_field',
                                                  })
        }

knowledge/views.py
# -*- coding: utf-8 -*-

from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views import View

from shop.functions import prepare_page
from .models import *
from .forms import QuestionForm, ResponseForm, QuestionItemForm


def index(request, action='all'):
    items = Question.objects.filter().order_by("-pk")
    if request.user.is_authenticated:
        if action == "my":
            items = items.filter(user=request.user)
        elif not request.user.is_staff:
            items = items.filter(Q(is_public=True)|Q(user=request.user))
    else:
        items = items.filter(is_public=True)
        
    page, page_range = prepare_page(request, items)
    return render(request, "knowledge/index.html",
                  {"page":page, "page_range":page_range,
                   "action":action})
    

def category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    items = Question.objects.filter(is_public=True, categories=category)
    page, page_range = prepare_page(request, items)
    return render(request, "knowledge/category.html",
                  {"page":page, "page_range":page_range,})


def question(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    print (q.item)
    if not q.is_public:
        if request.user.is_authenticated and not request.user.is_staff:
            if q.user != request.user:
                raise Http404
            
    responses = Response.objects.filter(question=q,
                                        accepted=True).order_by('added')
    if request.user.is_staff:
        responses = Response.objects.filter(question=q).order_by('added')
        
    return render(request, "knowledge/question.html",
                  {"q":q, "responses":responses, "form":ResponseForm()})


def response(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    form = ResponseForm(request.POST)
    if form.is_valid():
        resp = form.save(commit=False)
        resp.question = q
        resp.user = request.user
        if request.user.is_staff:
            resp.accepted = True
        resp.save()
        return HttpResponseRedirect(
            reverse('knowledge:question', kwargs={"question_id":q.pk}))
    raise Http404

    
class AskView(View):
    form_class = QuestionForm
    template_name = 'knowledge/ask.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name,
                      {'form': QuestionForm()})

    def post(self, request, *args, **kwargs):
        if request.POST.get('item', False):
            form = QuestionItemForm(request.POST)
        else:
            form = QuestionForm(request.POST)
        if form.is_valid():
            q = form.save(commit=False)
            q.user = request.user
            q.save()
            return HttpResponseRedirect(
                reverse('knowledge:question', kwargs={"question_id":q.pk}))

        return render(request, self.template_name, {'form': form})


@staff_member_required
def response_moderate(request, response_id, action):
    resp = get_object_or_404(Response, pk=response_id)
    if action == "hide":
        resp.accepted = False
    if action == "accept":
        resp.accepted = True
    resp.save()
    return HttpResponseRedirect(
        reverse('knowledge:question', kwargs={"question_id":resp.question.pk}))


@staff_member_required
def question_moderate(request, question_id, action):
    q = get_object_or_404(Question, pk=question_id)
    if action == "hide":
        q.is_public = False
    if action == "accept":
        q.is_public = True
        
    if action == "open":
        q.is_closed = False
    if action == "close":
        q.is_closed = True
    q.save()
    return HttpResponseRedirect(
        reverse('knowledge:question', kwargs={"question_id":q.pk}))
    

@login_required
def question_edit(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    if request.user != q.user and not request.user.is_staff:
        raise Http404
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=q)
        if form.is_valid():
            q = form.save()
            return HttpResponseRedirect(
                reverse('knowledge:question', kwargs={"question_id":q.pk}))
    else:
        form = QuestionForm(instance=q)
    

    return render(request, "knowledge/question-edit.html",
                  {'form': form, "question": q})


@login_required
def response_edit(request, response_id):
    resp = get_object_or_404(Response, pk=response_id)
    if request.user != resp.question.user and not request.user.is_staff:
        raise Http404
    if request.method == "POST":
        form = ResponseForm(request.POST, instance=resp)
        if form.is_valid():
            resp = form.save()
            return HttpResponseRedirect(
                reverse('knowledge:question',
                        kwargs={"question_id": resp.question.pk}))
    else:
        form = ResponseForm(instance=resp)
    

    return render(request, "knowledge/response-edit.html",
                  {'form': form, "response": resp})
    

@staff_member_required
def question_delete(request, question_id):
    q = get_object_or_404(Question, id=question_id)
    resp = Response.objects.filter(question=q).delete()
    q.delete()
    return HttpResponseRedirect(reverse('knowledge:index'))

templates/fasttech.com/knowledge/ask.html
{% extends "knowledge/base.html" %}
{% block knowledge_content %}

<h1> Задать вопрос</h1>
<hr />
<form id="ask_form" action="{% url 'knowledge:ask' %}" method="post" class="pure-form pure-form-stacked">{% csrf_token %}

	{% include "knowledge/form.html" %}
	<div class="pure-controls">
		<button class="pure-button pure-button-primary" id="id_login" type="submit">Задать вопрос в поддержку</button></p>
	</div>
	<p>
		Прежде чем задать вопрос, ознакомьтесь с <a href="https://fastek.link/pages/page/faq/">частыми вопросами</a>.
	</p>
</form>


{% endblock %}

templates/fasttech.com/knowledge/base.html
{% extends "base.html" %}

{% block title %}База знаний {% block add_title %}{% endblock %} | Поддержка{% endblock title %}
{% block extra_headers %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/knowledge.css">
  {% endblock %}

  {% block content %}
  <div id="wrpr">
    <div class="pure-u-2-3 main-content">
      {% block knowledge_content %}
      {% endblock %}
    </div>
    <div class="pure-u-1-5 sidebar" style="text-align:right;">
      {% block sidebar %}
		  {% if user.is_authenticated %}
			  <a href="{% url 'knowledge:index' action='my' %}">Мои вопросы</a>
			  <br />
		  {% endif %}
      <a href="{% url 'knowledge:index' %}">Все вопросы</a>
      <br />
	  <!-- 
        {% load knowledge_tags %}
		{% get_knowledge_categories_list %}
        {% for c in knowledge_categories_list %}
        <a href="{% url 'knowledge:category' category_id=c.id %}">{{ c }}</a>
        <br />
        {% endfor %}
		 -->
		<br />
		{% if user.is_authenticated %}
			<br />
			<a class="pure-button pure-button-primary" href="{% url 'knowledge:ask' %}">Задать вопрос</a>
		{% endif %}

      {% endblock %}
    </div>
  </div>
      
  {% endblock content %}

templates/fasttech.com/knowledge/form.html
  <fieldset> 
    <div class="pure-control-group">
      {% for field in form %}
      <div class="fieldWrapper">
	{{ field.errors }}
	{{ field.label_tag }}

	{% if field.help_text %}
	<span class="pure-form-message-inline">{{ field.help_text|safe }}</span>
	{% endif %}

        {{ field }}
        <br />
      </div>
      {% endfor %}

    </div>
  </fieldset>

templates/fasttech.com/knowledge/index.html
{% extends "knowledge/base.html" %}
{% block knowledge_content %}

    <div class="pure-u-1">
		{% if action == "my" %}
			<h1 class="-title">Мои вопросы:</h1>			
		{% else %}
			<h1 class="-title">Поддержка пользователей FASTEK, общие вопросы</h1>
		{% endif %}
    </div>

	
	<ul>
		{% for q in page %}
			<li>
				<a href="{% url 'knowledge:question' question_id=q.pk %}">#{{ q.id }} - {{ q }}</a>
				&mdash;
				{{ q.response_count_str }}
                                {% if user.is_staff %}
                                <span class="small" style="float:right;">
                                      от {{ q.user }}
                                      <a href="{% url 'knowledge:question_delete' question_id=q.id %}">удалить</a>
                                </span>
                                {% endif %}
			</li>
		{% endfor %}
	</ul>
	{% include "paginator.html" %}
{% endblock %}

templates/fasttech.com/knowledge/question-edit.html
{% extends "knowledge/base.html" %}
{% block knowledge_content %}

<h1>Редактирование вопроса:</h1>
<hr />
<form id="ask_form" action="{% url 'knowledge:question_edit' question_id=question.pk %}" method="post" class="pure-form pure-form-stacked">{% csrf_token %}

	{% include "knowledge/form.html" %}
	<div class="pure-controls">
		<button class="pure-button pure-button-primary" id="id_login" type="submit">Изменить</button></p>
	</div>
	<p>
	</p>
</form>


{% endblock %}

templates/fasttech.com/knowledge/question.html
{% extends "knowledge/base.html" %}
{% load knowledge_tags %}
{% block knowledge_content %}

<div class="pure-u-1">
  <h1>{{ q.title }}{% if not q.is_public %}<br /><span class="small">вопрос виден только вам и менеджеру</span>{% endif %}</h1>
</div>
{% if q.item %}
<span class="small">
Вопрос по товару: <a href="{% url 'item' item_name=q.item.title item_pk=q.item.pk %}">{{ q.item }}</a></span>
{% endif %}
<p>{{ q.description|markdown_filter|safe }}</p>

{% if user.is_staff %}
<div class="info">
  User: {{ q.user }}<br />
  {% if q.is_public %}
  Вопрос виден всем, <a href="{% url 'knowledge:question_moderate' question_id=q.pk action='hide' %}">скрыть?</a>
  {% else %}
  Вопрос виден только пользователю, <a href="{% url 'knowledge:question_moderate' question_id=q.pk action='accept' %}">открыть всем?</a>
  {% endif %}

  <br />
  {% if q.is_closed %}
  Вопрос закрыт, <a href="{% url 'knowledge:question_moderate' question_id=q.pk action='open' %}">открыть?</a>
  {% else %}
  Вопрос открыт, <a href="{% url 'knowledge:question_moderate' question_id=q.pk action='close' %}">закрыть?</a>
  {% endif %}


  <a href="{% url 'knowledge:question_edit' question_id=q.id %}">изменить</a>
  <br />
</div>
{% else %}
{% if user == q.user %}
<a href="{% url 'knowledge:question_edit' question_id=q.id %}">изменить</a>
{% endif %}
{% endif %}

<hr />
{% for r in responses %}
	<div class="response{% if r.accepted %}{% else %} not-accepted {% endif %}">
		<div class="info{% if r.user.is_staff %} info-admin {% endif %}">{% if r.user.is_staff %}Админ {% else %}Пользователь {% endif %}<em>{{ r.added }}</em> добавил ответ:
  </div>
  <p>{{ r.description|markdown_filter|safe }}
  </p>
  {% if user.is_staff %}
  <div class="info">
    {% if r.accepted %}
    Ответ принят, <a href="{% url 'knowledge:response_moderate' response_id=r.pk action='hide' %}">скрыть?</a>
    {% else %}
    Ответ скрыт, <a href="{% url 'knowledge:response_moderate' response_id=r.pk action='accept' %}">принять?</a>
    {% endif %}

    <a href="{% url 'knowledge:response_edit' response_id=r.id %}">изменить</a>                                                
  </div>
  {% else %}
  {% if user == q.user %}
  <a href="{% url 'knowledge:response_edit' response_id=r.id %}">изменить</a>
  {% endif %}
  
  {% endif %}
  
</div>
{% endfor %}


{% if q.is_closed %}
<div style="text-align:right"><em class="small">вопрос закрыт</em></div>
{% else %}
<form id="password_form" action="{% url 'knowledge:response' question_id=q.pk %}" method="post" class="pure-form pure-form-stacked">{% csrf_token %}

{% include "knowledge/form.html" %}
<div class="pure-controls">
  <button class="pure-button pure-button-primary" id="id_login" type="submit">Ответить</button></p>
</div>
</form>
{% endif %}
{% endblock %}

templates/fasttech.com/knowledge/response-edit.html
{% extends "knowledge/base.html" %}
{% block knowledge_content %}

<h1>Редактирование ответа:</h1>
<hr />
<form id="ask_form" action="{% url 'knowledge:response_edit' response_id=response.id %}" method="post" class="pure-form pure-form-stacked">{% csrf_token %}

	{% include "knowledge/form.html" %}
	<div class="pure-controls">
		<button class="pure-button pure-button-primary" id="id_login" type="submit">Изменить</button></p>
	</div>
	<p>
	</p>
</form>


{% endblock %}